### ISSUE TITLE
Settings aren't referenced

### ISSUE THREAD

**Issue by FlorianX** [mmunz/c1_adaptive_images#10]
see the "remember" section on the following link  https://docs.typo3.org/typo3cms/TyposcriptSyntaxReference/8.7/Syntax/TypoScriptSyntax/Index.html#references-the-sign

> References are only resolved for Content Objects, otherwise references are not resolved. For example, you cannot use a reference < plugin.tx_example.settings.foo to find the value of foo. The value you get will be just < plugin.tx_example.settings.foo instead.

So this change cases settings to break

**Comment by mmunz** [comment]
D'oh! Thanks for noticing and reporting. I also reverted removal of the additional settings. People might already use them in their templates.
