### ISSUE TITLE
FileReference Error

### ISSUE THREAD

**Issue by rowild** [mmunz/c1_adaptive_images#12]
When using this:
```
<ai:getCropVariants file="{file}" />
```

I keep getting this error:
```
Call to undefined method TYPO3\CMS\Extbase\Domain\Model\FileReference::hasProperty() 

Error thrown in file
/.../typo3conf/ext/c1_adaptive_images/Classes/ViewHelpers/GetCropVariantsViewHelper.php in line 56.
```

TYPO3 8.7.26, php 7.2
namespace included

It seems I have to transfer some crop values. I do have a fal image in my own extension, and it has crop values defined - the respective options to crop for the various breakpoint are visible, useable, editable and saved...

PS: I am new to this extension and in the context of TYPO3 totally confused with the whole responsive image idea (but I am not, when it comes to FE dev!)

**Comment by rowild** [comment]
...and when using the ai:image vh, I get this error:

```
Argument 1 passed to C1\AdaptiveImages\Utility\CropVariantUtility::setCropVariantCollection() must implement interface TYPO3\CMS\Core\Resource\FileInterface, instance of TYPO3\CMS\Extbase\Domain\Model\FileReference given, called in /.../ext/c1_adaptive_images/Classes/Utility/Placeholder/ImagePlaceholderUtility.php on line 38 
```

This is so weird, because the same setup works with sms-responsive-images... what am I doing wrong?

**Comment by mmunz** [comment]
@rowild Is the file you are using here really an instance of File or FileReference?
I just added better checks in these viewhelpers in master (checking if the object passed is implementing FileInterface). Can you please test with master and see if this throws an error then?

Edit: Now i see, that you have a TYPO3\CMS\Extbase\Domain\Model\FileReference here. It might just work if you use file="{file.originalResource}" then.

**Comment by rowild** [comment]
@mmunz Thank you for your speed-lightning-fast response! Awesome!

I tried master, but same result. And yes, what is sent is a of type `FileReference`. See attached images. 
All that comes to my mind when looking at the error message is, that the ext wants a fileINTERFACE, but I can only send a fileREFERENCE. I am not very familiar with how interface work completely and if the recognises the filetype they are an interface for, but could this be the culprit?

Fluid:
![Bildschirmfoto 2019-06-10 um 13 33 47](https://user-images.githubusercontent.com/213803/59193062-c6dfa400-8b84-11e9-9351-b5c31e44bec2.png)

Error Message:
![Error-Message](https://user-images.githubusercontent.com/213803/59193077-d101a280-8b84-11e9-8bc4-247e1472a850.png)

**Comment by rowild** [comment]
@mmunz anymore insights on this topic?

**Comment by mmunz** [comment]
@rowild the problem seems to be that you are using TYPO3\CMS\Extbase\Domain\Model\FileReference which does not implement FileInterface. Does your file have a property file.originalResource or similar, which should be either TYPO3\CMS\Core\Resource\File or TYPO3\CMS\Core\Resource\FileReference?

**Comment by rowild** [comment]
Hmm... that' weird. Why is "originalfile" "null"? Need to check that. Any ideas to clarify most welcome!
