### ISSUE TITLE
Crash if ImageViewHelper is called on non-existent image

### ISSUE THREAD

**Issue by TheJotob** [mmunz/c1_adaptive_images#3]
If the ImageViewHelper is called for a non-existent file, the page crashes with an error
`Call to undefined method TYPO3\CMS\Core\Resource\ProcessedFile::setMissing()`

I could narrow it down to the statement `$processedImage->getContents()` in Line 122 in C1\AdaptiveImages\ViewHelpers\Placeholder\ImageViewHelper.

I would suggest to check if the original image exists and if not return an empty URI. That way in the frontend it shows an empty error, but doesn't crash typo3. I can provide you a pull request if you want.

**Comment by mmunz** [comment]
@TheJotob i think the commit above addresses this. Instead of an empty URL i return the public URL of the image which always exists, even if the image file is missing.
