### ISSUE TITLE
Missing Fluid Declaration in Documentation

### ISSUE THREAD

**Issue by WiesBen** [mmunz/c1_adaptive_images#7]
I run into an error because you need to set 

xmlns:ai="http://typo3.org/ns/C1/AdaptiveImages/ViewHelpers"

first in any used fluid template. Maybe this should be noted in the documentation?

**Comment by mmunz** [comment]
Thanks. I'll prepare a new release also including the fix for global registered namespace: c3b6440d8a788b1124dc0f1a4c2745f85e1a304b
